project:
  type: website
  output-dir: _site

website:
  title: "STRATEGIOS"
  description: "Swedish Public Sector Strategy Research"
  site-url: https://strategios.se

  navbar:
    background: dark
    foreground: light

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true

execute:
  freeze: auto
